name: Run Pending Scans

# ── triggers ──────────────────────────────────────────────────────
on:
  schedule:
    - cron: '*/2 * * * *'       # every 5 min UTC
  push:
    branches: [ main ]
  workflow_dispatch: {}          # manual “Run workflow” button

# ── single job ────────────────────────────────────────────────────
jobs:
  scan:
    concurrency:
      group: scan-cron           
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      # 1) pull repo
      - uses: actions/checkout@v4

      # 2) Node 20 with npm cache
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      # 3) deps
      - run: npm ci

      # 4) build TypeScript worker → dist-worker/
      - name: Build worker
        run: npm run build-worker           # tsc --project tsconfig.worker.json

       # 5) execute compiled JS directly (so it picks up GH secrets)
      - name: Execute worker
        run: node dist-worker/app/api/workers/run-scans.js
        env:
          SUPABASE_URL:       ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          RESEND_API_KEY:     ${{ secrets.RESEND_API_KEY }}